### ISSUE TITLE
What is the rank of actual trajectories?

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#10]
On the IJCAI15 data, we can enumerate all trajectories of length 3 and 4, and their associated ILP objective. Where do the trajectories that actually occur in the data appear in the list sorted by this score?

**Comment by chengsoonong** [comment]
FILE_LIST_NAME cannot be found in the repository (plot_enumseq.py)

**Comment by cdawei** [comment]
section 6 of notes.py has description of how to use plot_enumseq.py
