### ISSUE TITLE
SSVM prediction: prove the inference problem is NP-hard

### ISSUE THREAD

**Issue by cdawei** [chengsoonong/digbeta#105]
Prove the inference problem in SSVM, i.e., find a maximum weighted simple path with exactly k edges in a complete directed graph given a source node, is NP-hard.

**Comment by cdawei** [comment]
Helpful references:
- shortest path with k edges https://courses.cs.washington.edu/courses/cse421/06au/slides/Lecture21/Lecture21.pdf
- http://stackoverflow.com/questions/15714505/shortest-path-in-an-undirected-graph-that-visits-k-vertices

**Comment by chengsoonong** [comment]
This is currently out of scope of this project.
