### ISSUE TITLE
What are trajectories with highest score?

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#11]
To understand how to design better objective functions, we should visualise the trajectories with highest score and compare them to some real trajectories in the IJCAI15 dataset.

It is unclear to me which tool to use to show the tracks.

**Comment by chengsoonong** [comment]
Looking at plot_enumseq.py
- Why are there boxplots with zero variance? I suspect that the exhaustive enumeration is not exhaustive. For example 1403 only contains two generated trajectories.
- Only considering the trajectories with the same length (3 POIs), the actual trajectories are either only the top or bottom ranked item. Surprising, needs explanation.
- Does it make sense to compare scores from trajectories of different lengths?

So far, this is looking at the scores. It would be useful to understand the actual trajectories themselves.

**Comment by chengsoonong** [comment]
This could potentially be solved by a good visualisation (issue #20).

**Comment by cdawei** [comment]
Please refer to issue #20.
