### ISSUE TITLE
ListViterbi == ILP ?

### ISSUE THREAD

**Issue by cdawei** [chengsoonong/digbeta#112]
Given the same weight vector for SSVM, does the prediction by the list Viterbi algorithm is the same as that of ILP (assuming no ties)? 
Write down the proof.

**Comment by lexingxie** [comment]
do list Viterbi find the 'best' solution, 
but ILP doesn't (in some limited running time) ?

but of course the above doesn't make sense, as list viterbi is a poly-time algorithm, but ILP isn't

**Comment by cdawei** [comment]
> do list Viterbi find the 'best' solution, but ILP doesn't (in some limited running time) ?

Given limited running time, both algorithms could fail to find the 'best' solution, in fact, for long trajectories (e.g., length > 15), ILP is more efficient than list Viterbi in practice.

> list viterbi is a poly-time algorithm, but ILP isn't

The time complexity of list Viterbi is pseudo-polynomial (i.e., it depends on N, not logN), according to http://www.eng.biu.ac.il/~goldbej/papers/ijcai01.pdf

**Comment by chengsoonong** [comment]
I think give up on this.
