### ISSUE TITLE
Transition matrix for time at POI

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#12]
Design a binning procedure that discretises the time spent at POI (a feature used for recommendation). One possibility is 10 log spaced bins (i.e. uniform in the logarithm of the time, taking care of zero).

This allows us to study the transition matrix corresponding to this feature:
- What is the variation between users?
- Do users spend a long time at POI followed by a short time at another POI?
- How do we compare this transition matrix with the POI type transition matrix?

**Comment by chengsoonong** [comment]
Closed by a30ce9a1c6651bd798fb536639e516b5cba75d61

**Comment by chengsoonong** [comment]
Please say in your commit the issue number. Also describe in the commit message which file(s) I need to look at to be able to answer the questions above.

**Comment by cdawei** [comment]
Transition matrix for time at POI is available in section 3.4 of ijcai15.ipynb
