### ISSUE TITLE
Prediction without length constraint

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#126]
Right now a query is a (start POI, length) tuple, and hence SSVM only has to predict a sequence of the given length. An alternative is a query that only is (start POI). Before implementing this, we need to check that the scores of the SSVM are comparable for predictions of different length.

**Comment by cdawei** [comment]
We can get rid of the length, which is a simple constraint, and add other constraints, e.g. time, budget. 
However, it is not clear how to model the time and cost/budget.
If the query contains only the start point, and without any other constraints, then we probably need to scoring trajectories such that scores are normalised over length.

**Comment by cdawei** [comment]
Close this issue as we won't fix it.
