### ISSUE TITLE
Bellman Ford with weights

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#14]
For tour recommendations, we would like to find good paths on a graph that has weights on nodes and edges. [stackoverflow] One way to solve this would be to convert the graph into a new graph in which only edges are weighted, not vertices. To do this, you can split each node apart into two nodes as follows. For any node v, make two new nodes, v1 and v2. All edges that previously entered node v now enter node v1, and all edges that leave node v now leave v2. Then, put an edge between v1 and v2 whose cost is the cost of node v1.

In this new graph, the cost of a path from one node to another corresponds to the cost of the original path in the original graph, since all edge weights are still paid and all node weights are now paid using the newly-inserted edges.

Dijkstra might be enough, but it might be that we need Bellman Ford.

**Comment by cdawei** [comment]
NetworkX could be a useful library for this issue, https://networkx.github.io/
I had been using it to analyse social networks, it implements many graph algorithms including Bellman-Ford: http://networkx.readthedocs.org/en/stable/reference/algorithms.shortest_paths.html

**Comment by cdawei** [comment]
Close issue.
