### ISSUE TITLE
Writing: misc

### ISSUE THREAD

**Issue by cdawei** [chengsoonong/digbeta#147]
Explicitly describe that:
- "SP" duplicates examples for multiple ground truths and why there's better models (e.g. "SR")
- all methods have access to the start POI
- the underlying structure is a tree so that efficient loss augmented inference is possible given decomposition of loss

Improve those: 
- describe joint feature decomposition earlier
- the description of features used for each method
- the description of the way training and test sets are constructed

**Comment by chengsoonong** [comment]
Resolved in cd04f49
