### ISSUE TITLE
K shortest paths

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#16]
For both simulation of tours and understanding the uncertainty in the parameter estimates, it is often useful to find a number (k) of paths which can arise. This is an extension of Dijkstra which keeps track of the top k paths, instead of just the shortest one.

https://en.wikipedia.org/wiki/K_shortest_path_routing

**Comment by chengsoonong** [comment]
From a Markov model perspective, one can consider a Viterbi decoding that keeps track of the top K paths, as well as the confidence score that we have for each path. The generalisation of Viterbi to allow for multiple paths is called List Viterbi, and the generalisation that also computes a confidence score is called Soft Viterbi.

http://dx.doi.org/10.1109/26.380046

**Comment by cdawei** [comment]
Close issue.

**Comment by cdawei** [comment]
When the total number of POIs is considerably larger than the requested number of POIs in a query, the results of List Viterbi probably (but no guarantee) contain one trajectory without sub-tours, which is helpful to circumvent the NP-hardness when employing TSP sub-tour elimination constraints.

**Comment by cdawei** [comment]
Some references:
- Shortest paths with a fixed number of edges  https://courses.cs.washington.edu/courses/cse421/06au/slides/Lecture21/Lecture21.pdf
- http://stackoverflow.com/questions/15714505/shortest-path-in-an-undirected-graph-that-visits-k-vertices

**Comment by cdawei** [comment]
Closed by #96
