### ISSUE TITLE
Script to set up data

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#17]
For the IJCAI15 paper, the data is public. There should be a script that downloads the data and sets it up such that the notebooks notes.ipynb and melbourne.ipynb can run.

The data for the city of Melbourne may need some manual management for the moment, but the 4 other cities should be ok.

**Comment by cdawei** [comment]
The geo-coordinates of photos, which are used to compute the travel cost in the model, are not available from the dataset provided by the authors, however, they can be queried from the original YFCC dataset by using photo id which is available in the authors' dataset, though very time-consuming.

**Comment by cdawei** [comment]
Data files contain POI ID and coordinates for each city should be available in a 'data' directory.
