### ISSUE TITLE
Are there different trajectories with same (start, end)?

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#21]
In the actual trajectories from the IJCAI15 paper, do you ever see any trajectories that start and end at the same locations, but take different paths? If so, it would be good to understand why this happens.

**Comment by cdawei** [comment]
These kind of trajectories do not exist in the IJCAI15 paper's dataset after checking. Also, trajectories with sub-tour were not found either.

**Comment by chengsoonong** [comment]
It seems that such trajectories exist.
- Visualise all trajectories with more than one occurrence (can be same or different user)
- Visualise all trajectories with same (start, end) but different paths
- Visualise the most common edges.

**Comment by chengsoonong** [comment]
Create a table with all (start, end) pairs with more than one actual trajectory. This table has three columns:
- (start, end)
- number of actual trajectories
- number of users 

Sort table by number of actual trajectories.

**Comment by cdawei** [comment]
Notebook traj_visualisation.ipynb did this, commit hash 2db6d36c938cdddacf42fc5bd8e109a7bb95f21e
