### ISSUE TITLE
timestamp processing error for photo trajectories (assigned to cdawei)

### ISSUE THREAD

**Issue by lexingxie** [chengsoonong/digbeta#31]
the "longest" trajectory by distance started in 2009 but ended in 2011 with 4 photos. This is impossible!!

see photo info below, and link to google map is here
https://www.google.com/maps/d/edit?mid=z8aacUEV5ldM.kGrAirNPcXgM&usp=sharing

Trajectory_ID: 9178
Photo_ID: 3558147582
User_ID: 48894056@N00
Timestamp: 2009-05-24 09:48:46
Coordinates: (143.666453, -38.758333)
Accuracy: 14
URL: http://www.flickr.com/photos/48894056@N00/3558147582/

Photo_6276179396
Trajectory_ID: 9178
Photo_ID: 6276179396
User_ID: 48894056@N00
Timestamp: 2011-10-10 17:04:08
Coordinates: (146.964833, -36.737833)
Accuracy: 16
URL: http://www.flickr.com/photos/48894056@N00/6276179396/

**Comment by lexingxie** [comment]
the timestamp sequence is as follows:

Trajectory_ID: 9178

75004    2009-05-24 09:48:46
75005    2011-10-09 14:53:43
75006    2011-10-10 17:04:08
75007    2011-10-10 18:56:43

**Comment by chengsoonong** [comment]
I guess we should probably move this issue to flickr-photo repository.

**Comment by cdawei** [comment]
Moved to  flickr-photo repository.
