### ISSUE TITLE
finding good features

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#35]
Do an experiment who identify good features. Candidates:

Single node features:
- User Interest (time)
- User interest (frequency)
- POI Popularity
- Travelling Distance

Trajectory probability based on the transition probabilities between different POI categories and the following rules for choosing a specific POI within certain category:
- The Nearest Neighbor of the current POI
- The most Popular POI
- A random POI choosing with probability proportional to the reciprocal of its distance to current POI
- A random POI choosing with probability proportional to its popularity

**Comment by chengsoonong** [comment]
In commit fe8717796d4d549ff4b7fc005da7bcb0a6816900, when testing a single feature, only three weights really make sense: negative, zero, and positive. Looking at the grid in steps of 0.05 is just wasting computation time. Or is there a reason why 0.05 and 0.1 should give a different ranking of the trajectories?

**Comment by cdawei** [comment]
Solved by commit 19929124e152a63436ebc33c8dcba8402d64f8d0
