### ISSUE TITLE
Create trajectory datasets from IJCAI15 data

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#44]
These should be filtered for length > 3 so that the IJCAI15 experiment is meaningful.

One possible design is to have two tables:
1. Features of POIs: lat, long, category, etc.
2. list of POIs (trajectories). E.g for Toronto, this is 290 rows.

**Comment by cdawei** [comment]
Implemented in notebook data_preprocess.ipynb in commit 6537d7222ac2fcd1dfddc06eff3b3afbf55aa958.
Close issue.
