### ISSUE TITLE
Recommend POIs = recommend trajectory of length 1?

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#45]
For very short trajectories of length 1, is this the same as the basic recommender system problem of recommending POIs?

With a bit of care and extra structuring, this could make a good undergrad project.

**Comment by cdawei** [comment]
This could be the first or second cases as described in the [cikm'16 work](https://arxiv.org/abs/1608.07051), which are normally dealt with different techniques.
