### ISSUE TITLE
Write the probabilistic model that combines ranking & transition probabilities

### ISSUE THREAD

**Issue by cdawei** [chengsoonong/digbeta#54]

**Comment by lexingxie** [comment]
Justify this equation in your write up. 

![image](https://cloud.githubusercontent.com/assets/2434228/12965099/e16e0280-d0a7-11e5-9264-d59581e84ab9.png)

**Comment by cdawei** [comment]
Commit 7cb85f243ced5bb2c81d7da1328c2e1698e8a4c7 try to justify the optimisation objective.
