### ISSUE TITLE
factorised transition matrix: duplicate or divide? 

### ISSUE THREAD

**Issue by lexingxie** [chengsoonong/digbeta#56]
write out the "Kronecker" product of the factorised transition matrix 
fully justify the case when two POIs have exactly the same feature -- what should be done and why.

**Comment by lexingxie** [comment]
basically, write out cases when col/rows are empty 
and when there's more than one actual POI that correspond to col/row

![image](https://cloud.githubusercontent.com/assets/2434228/12966079/50d88fb2-d0af-11e5-83b3-8bd7a1094ccb.png)

**Comment by cdawei** [comment]
Commit 2df79c6c58fd5840a989eb5ef70873f0ac50716a deal with this issue.
