### ISSUE TITLE
methods for learning user-specific rankSVM 

### ISSUE THREAD

**Issue by lexingxie** [chengsoonong/digbeta#57]
Frustratingly Easy Domain Adaptation
Hal Daumé III
http://arxiv.org/abs/0907.1815

An Empirical Analysis of Domain Adaptation Algorithms for Genomic Sequence Analysis
Gunnar et al. 
http://papers.nips.cc/paper/3407-an-empirical-analysis-of-domain-adaptation-algorithms-for-genomic-sequence-analysis

**Comment by lexingxie** [comment]
hint: alex used one of these methods in his AAAI paper.

**Comment by cdawei** [comment]
We can close this issue, see #78
