### ISSUE TITLE
paths vs walks

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#58]
Define a path to be a trajectory with a unique set of vertices (no cycles). Call the trajectory with tottering a walk (see e.g. J.P Vert's talks on graph kernels)

Write a function to detect whether a walk has tottering.

E.g. simple path = path
[16, 7, 22, 23, 29]
E.g. path with tottering = walk
[16, 22, 23, 22, 29]

Write a test function to confirm that when dynamic programming returns a path, it is the same path that is returned by the integer program. If the empirical results turn out to be true for lots of graphs, then it may be worth proving the theorem.

Is the dynamic programming solution faster than the ILP solution for our datasets? Write a small experiment to confirm.

**Comment by chengsoonong** [comment]
This is related to issue #77

**Comment by cdawei** [comment]
Close this issue, see #96
