### ISSUE TITLE
User specific weighting

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#61]
By upsampling user's trajectories in the training sets.

**Comment by cdawei** [comment]
Section 6.1 of notebook traj_user_specific.ipynb, 100X of trajectories of a specific user (except the one used to validate) as well as 1X of trajectories of other users was used to training.

**Comment by cdawei** [comment]
The result of user specific upsampling was a bit better (+2%) than user agnostic setting, both with short trajectories, and it was slightly worse (-1%) than user agnostic setting without short trajectories.
