### ISSUE TITLE
Latex table for experimental results

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#62]
No numbers

**Comment by cdawei** [comment]
The second section of method.tex lists 9 methods for comparison.

**Comment by chengsoonong** [comment]
What about user agnostic vs user specific recommendations?
How about the other 4 cities?
I suggest not reporting Kendall's tau for now.
If there are vast differences in compute time (training, prediction) might be worth reporting.

**Comment by cdawei** [comment]
Finished by commit 4b5e9cac1f49f32aee29070dc6b104e8a1dd1ed3
