### ISSUE TITLE
experiment on users with lots of trajectories

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#66]
- filter data to have a subset with more than e.g. 5 trajectories
- report results and tune hyper-param on this subset 
- hyper-parameter range, in multiplicative steps of 2
  [1, 2, 4, ... #trajectories, 2x#trajectories, 4x#trajectories]

**Comment by cdawei** [comment]
Results available on notebook parse_results.ipynb in commits a583ee1b7c3b8665790b7ea5d473cbc622ca31fd and 7b4ce9ac6beb3079ca2753685bba3bea901e3414.
Close issue.
