### ISSUE TITLE
figure out the difference w. IJCAI paper

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#67]
Cheng to write to Jeff 

ask for predictions, or implementation, or ...

**Comment by chengsoonong** [comment]
Emailed Kwan Hui and Jeff.

**Comment by cdawei** [comment]
Close issue #67, reproduce is available in notebook ijcai15-KH.ipynb in commit 6032d2e8ac930fc51a35e8a8b5f428fd045a2fc2.
