### ISSUE TITLE
Filename generator in experiments

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#74]
Write a small module whose only purpose is to generate file names for your experiments. Essentially, refactor all your code that is producing names to one module.

So, instead of each notebook having some rule for concatenating strings to generate a file name (which is hard to maintain), each notebook calls functiond that returns a file name given the parameter settings.

**Comment by cdawei** [comment]
Close issue #74, section 2 of notebook parse_results.ipynb fix it.
