### ISSUE TITLE
pystruct: use rankSVM features as unary features

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#75]
Removes training of rankSVM, and gives more interpretable weights.

**Comment by cdawei** [comment]
It seems to be nontrivial to remove training of rankSVM, as it provides a way to generate node features when prediction, i.e., duplicate the ranking probabilities of all POIs (traj_length - 2) times.
If rankSVM was not trained, for prediction, when only (start, end, length) are known, there needs a way to generate node features.

**Comment by lexingxie** [comment]
this indeed non-trival. 

Therefore as suggested in our meeting yesterday -- keep the current implementation for now (until the recsys deadline), and then implement/resolve this issue after the submission deadline.

**Comment by cdawei** [comment]
Merge with issue #81
