### ISSUE TITLE
SSVM - ILP

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/digbeta#77]
It turns out that self loops and tottering is hurting predictions. SSVM does not take care of this. To avoid tottering, we need to solve an ILP.

The task is to update structured prediction learning to allow for an ILP inside.

**Comment by chengsoonong** [comment]
Regarding the idea for a new structured SVM training. Based on discussion with Lexing, it seems to not be so useful to have an ILP inside the training procedure. There needs to be something cheap and fast for generating the cutting planes. But first, it seems worthwhile to learn about cutting planes.

Here's two papers about SSVM cutting planes
https://www.cs.cornell.edu/people/tj/publications/joachims_etal_09a.pdf
http://www.pletscher.org/papers/lacostejulien2013fwstruct.pdf

The "max" view of cutting planes can sometimes be misleading. In fact, any cut will work. Here's a paper that uses a different cut (for multiple kernel learning, not SSVM).
http://www.ong-home.my/papers/wulff14accpm-mkl.pdf
I do not know how the analytic center cut might work for SSVM (it may not).

The general idea would be to use fast ways for approximately solving the path problem (using standard methods from TSP optimisation), and use them as cutting planes.

**Comment by cdawei** [comment]
TSP heuristics could be used when training SSVM to avoid sub-tours.

**Comment by cdawei** [comment]
Related to #96

**Comment by cdawei** [comment]
Close this issue, see #111 and #112
