### ISSUE TITLE
SSVM training: do loss-augmented-inference using vanilla Viterbi

### ISSUE THREAD

**Issue by cdawei** [chengsoonong/digbeta#95]
Training a SSVM using cutting-plane methods (1-slack formulation).
Do loss-augmented inference using the vanilla Viterbi algorithm with Hamming loss (which means the most violated label may contain sub-tours).

**Comment by cdawei** [comment]
Implemented in 6cec41e

**Comment by chengsoonong** [comment]
I assume this issue is about implementing Viterbi. If so, please start a new one for adding the results to the LaTeX table.
