### ISSUE TITLE
SSVM prediction: do inference using a variety of algorithms

### ISSUE THREAD

**Issue by cdawei** [chengsoonong/digbeta#96]
Do inference for prediction with
- vanilla Viterbi algorithm, which permits sub-tours;
- list Viterbi algorithm, which iteratively find the next best path/walk;
- integer linear programming, which does not permit sub-tours;
- Christofides algorithm, a heuristic which does not permit sub-tours.

**Comment by lexingxie** [comment]
this issue is too big, break into several. 
we discussed list Viterbi today, may need  to spend more time and clarify all details. 

in the new issue, include test cases.

**Comment by cdawei** [comment]
It seems nontrivial to adapt the Christofides algorithm to the prediction inference, i.e., find a maximum weighted simple path with exactly k edges in a complete directed graph given a source node. 

Create a dedicated issue for it. Besides, greedy search as a baseline is worth a try.

There's also work to use/improve the Christofides algorithm in s-t path TSP http://dl.acm.org/citation.cfm?id=2818310

**Comment by cdawei** [comment]
vanilla Viterbi, list Viterbi, ILP and greedy search have been implemented in 6cec41e
